name: Setup Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  setup-kubernetes-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@0ad70e2299366b0e1552c7240f4e4567148f723e #v2.0.4
        with:
          # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
          version: v0.20.0
          # default value for event_name != workflow_dispatch
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4.1.0
        with:
          version: 'latest'

      - name: Install NGINX Ingress Controller
        run: |
          kubectl create namespace ingress-nginx
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx

      - name: Verify Ingress Controller installation
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s

      - name: Get Ingress Controller IP
        id: get_ingress_ip
        run: |
          INGRESS_IP=$(kubectl get svc --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV

      - name: Add .tx.test domain to /etc/hosts
        run: |
          echo "${{ env.INGRESS_IP }} example.tx.test" | sudo tee -a /etc/hosts

      - name: Create Ingress Resource
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: example-ingress
            namespace default
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: example.tx.test
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: example-service
                      port:
                        number: 80
          EOF

      - name: Verify Ingress Resource
        run: |
          kubectl wait --namespace default \
            --for=condition=ready pod \
            --selector=app=example-app \
            --timeout=120s

      - name: Ping ingress
        run: |
          ping example.tx.test
