name: Setup Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  setup-kubernetes-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@0ad70e2299366b0e1552c7240f4e4567148f723e #v2.0.4
        with:
          # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
          version: v0.20.0
          # default value for event_name != workflow_dispatch
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

      - name: Get Cluster info
        run: |
          kubectl cluster-info --context kind-kind

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4.1.0
        with:
          version: 'latest'

      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

      - name: Describe Ingress Controller
        run: |
          kubectl describe svc/ingress-nginx-controller -n ingress-nginx

      - name: Get Pods
        run: |
          kubectl get pods -n ingress-nginx
          kubectl describe pod ingress-nginx-controller -n ingress-nginx

      - name: Verify Ingress Controller installation
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=200s

      - name: Get Ingress Controller Logs
        if: always()
        run: |
          kubectl get pods -n ingress-nginx
          kubectl logs svc/ingress-nginx-controller -n ingress-nginx

      - name: Get Ingress Controller IP
        id: get_ingress_ip
        run: |
          INGRESS_IP=$(kubectl get svc --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV

      - name: Add .tx.test domain to /etc/hosts
        run: |
          echo "${{ env.INGRESS_IP }} example.tx.test" | sudo tee -a /etc/hosts

      - name: Create Test Ingress Resource
        run: |
          kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml

      - name: Ping ingress
        if: always()
        run: |
          # should output "foo-app"
          curl localhost/foo/hostname
          # should output "bar-app"
          curl localhost/bar/hostname
          
          # ping example.tx.test
