name: Tavern IRS API test on DEV

on:
  workflow_dispatch: # Trigger manually
  schedule:
    - cron: '0 1 * * 1-5' # At 01:00 on every day-of-week from Monday through Friday.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup env
        uses: ./.github/actions/setup-umbrella-env

      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          pip install pytest
          pip install py
          pip install tavern
          pip list

      - name: Run tests
        env:
          IRS_HOST: 'http://localhost:8080'
          IRS_ESS_HOST: 'http://localhost:8080'
          REGULAR_USER_API_KEY: 'password'
          ADMIN_USER_API_KEY: 'password'
          REGULAR_USER_API_KEY_ESS: 'password'
          ADMIN_USER_API_KEY_ESS: 'password'
          GLOBAL_ASSET_ID_AS_PLANNED: 'urn:uuid:0733946c-59c6-41ae-9570-cb43a6e4c79e'
          GLOBAL_ASSET_ID_ESS_AS_BUILT: 'urn:uuid:2c57b0e9-a653-411d-bdcd-64787e9fd3a7'
          BPN_ESS_AS_BUILT: 'BPNL00000003CRHK'
          BPN_ESS_INCIDENT: 'BPNS00000003B6LU'
          BPN_AS_PLANNED: 'BPNL00000003AYRE'
          GLOBAL_ASSET_ID_AS_BUILT: 'urn:uuid:4509ea7c-c8d2-41a1-83ca-c214ee34af6c'
          BPN_AS_BUILT: 'BPNL00000003AVTH'
        run: |
          python -m pytest local/testing/api-tests/irs-api-tests.tavern.yaml --junitxml=tavern-results.xml

      - name: Mask credentials
        if: always()
        run: |
          sed "s/access_tok.*:s = '.*'//g" tavern-results.xml | sed "s/Authorization: Bearer .*/Authorization:/g" | uniq > result.xml

      - name: Publish Tavern Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          files: |
            result.xml

      - name: setup env
        uses: ./.github/actions/umbrella-irs-logs
